# create-bitmap.py
"""
Example script to create a simple checkerboard BMP image for testing SDL_CreateWindowAndRenderer.
Usage: python3 create-bitmap.py
or directly run with:
python3 - <<'EOF'                                                                                                                                                                                           │
<CODE>
EOF

Generated by Claude Sonnet 4.6
"""
import struct

def write_bmp(filename, width=256, height=256, square_size=32):
    # BMP file format
    row_size = (width * 3 + 3) & ~3  # padded to 4 bytes
    pixel_data_size = row_size * height
    file_size = 54 + pixel_data_size

    # BMP header
    header = struct.pack("<2sIHHI", b"BM", file_size, 0, 0, 54)
    # DIB header (BITMAPINFOHEADER)
    dib = struct.pack(
        "<IiiHHIIiiII", 40, width, height, 1, 24, 0, pixel_data_size, 2835, 2835, 0, 0
    )

    rows = []
    for y in range(height):
        row = bytearray()
        for x in range(width):
            # checkerboard: alternate black/white based on square index
            if ((x // square_size) + (y // square_size)) % 2 == 0:
                row += b"\xff\xff\xff"  # white
            else:
                row += b"\x00\x00\x00"  # black
        # pad row to multiple of 4
        row += b"\x00" * (row_size - width * 3)
        rows.append(bytes(row))

    with open(filename, "wb") as f:
        f.write(header)
        f.write(dib)
        # BMP stores rows bottom-up
        for row in reversed(rows):
            f.write(row)


write_bmp("sample.bmp")
print("Created sample.bmp (256x256, 32px squares)")
